CREATE TABLE IF NOT EXISTS Usuarios (
    Id SERIAL PRIMARY KEY,
    NombreCompleto VARCHAR(100) NOT NULL,
    Correo VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL,
    Rol VARCHAR(50) NOT NULL,
    CreadoEn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
